name=rgBtn
version=1.0.0
author=Richard Goutorbe <pub@reseau.org>
maintainer=Richard Goutorbe <pub@reseau.org>
sentence=A push button library.
paragraph=A push button library with blocking and non-blocking methods.
category=Signal Input/Output
url=https://github.com/rigou?tab=repositories
architectures=*
