# config_mqtt_prod.yaml - Production MQTT-controlled devices
# 2026-04-01

# Climatiseur Bureau v2.0.0
- switch:
    unique_id: "clim1v2-power"
    name: "clim1v2 Power"
    state_topic: "esp-5e8bd8/Power/get" # read the current state of the AC power
    command_topic: "esp-5e8bd8/Power/set" # turn the AC power on/off
    qos: 0
    payload_on: 1
    payload_off: 0
    optimistic: false
    device: {
      identifiers: ["clim1v2"],
      manufacturer: "rigou",
      model: "nodemcu",
      name: "clim1v2 Bureau",
      suggested_area: Bureau
    }
- number:
    unique_id: "clim1v2-temp"
    name: "clim1v2 Temperature"
    state_topic: "esp-5e8bd8/Temp/get" # read the current temperature
    command_topic: "esp-5e8bd8/Temp/set" # change the current temperature
    qos: 0
    device: {
      identifiers: ["clim1v2"],
      manufacturer: "rigou",
      model: "nodemcu",
      name: "clim1v2 Bureau",
      suggested_area: Bureau
    }
- sensor:
    unique_id: "clim1v2-version"
    name: "clim1v2 Version"
    state_topic: "esp-5e8bd8/Info/get"
    qos: 0
    value_template: "{{ value_json.app_version }}"
    device: {
      identifiers: ["clim1v2"],
      manufacturer: "rigou",
      model: "nodemcu",
      name: "clim1v2 Bureau",
      suggested_area: Bureau
    } 
- sensor:
    # extract the "ip" field of the json value of the "Info" topic
    # render the value on the dashboard as a string
    unique_id: "clim1v2-ip"
    name: "clim1v2 Ip"
    state_topic: "esp-5e8bd8/Info/get"
    qos: 0
    value_template: "{{ value_json.ip }}"
    device: {
      identifiers: ["clim1v2"],
      manufacturer: "rigou",
      model: "nodemcu",
      name: "clim1v2 Bureau",
      suggested_area: Bureau
    } 

# # Climatiseur Bureau v1.1.7
# - switch:
#     unique_id: "clim1-power-ooyeRai1"
#     name: "clim1 Power"
#     state_topic: "clim1/Power/get" # read the current state of the AC power
#     command_topic: "clim1/Power/set" # turn the AC power on/off
#     qos: 0
#     payload_on: 1
#     payload_off: 0
#     optimistic: false
#     device: {
#       identifiers: ["clim1"],
#       manufacturer: "rigou",
#       model: "nodemcu",
#       name: "Clim Bureau",
#       suggested_area: Bureau
#     }
# - number:
#     unique_id: "clim1-temp-aibiToo3"
#     name: "clim1 Temperature"
#     state_topic: "clim1/Temperature/get" # read the current temperature
#     command_topic: "clim1/Temperature/set" # change the current temperature
#     qos: 0
#     device: {
#       identifiers: ["clim1"],
#       manufacturer: "rigou",
#       model: "nodemcu",
#       name: "Clim Bureau",
#       suggested_area: Bureau
#     }
# - sensor:
#     unique_id: "clim1-version-Ahk2fooj"
#     name: "clim1 Version"
#     state_topic: "clim1/Info/get"
#     qos: 0
#     value_template: "{{ value_json.app_version }}"
#     device: {
#       identifiers: ["clim1"],
#       manufacturer: "rigou",
#       model: "nodemcu",
#       name: "Clim Bureau",
#       suggested_area: Bureau
#     } 

# Climatiseur Séjour
- switch:
    unique_id: "clim2-power-eiGhej0y"
    name: "clim2 Power"
    state_topic: "clim2/Power/get" # read the current state of the AC power
    command_topic: "clim2/Power/set" # turn the AC power on/off
    qos: 0
    payload_on: 1
    payload_off: 0
    optimistic: false
    device: {
      identifiers: ["clim2"],
      manufacturer: "rigou",
      model: "nodemcu",
      name: "Clim Séjour",
      suggested_area: SÃ©jour
    }
- number:
    unique_id: "clim2-temp-eisei9Ie"
    name: "clim2 Temperature"
    state_topic: "clim2/Temperature/get" # read the current temperature
    command_topic: "clim2/Temperature/set" # change the current temperature
    qos: 0
    device: {
      identifiers: ["clim2"],
      manufacturer: "rigou",
      model: "nodemcu",
      name: "Clim Séjour",
      suggested_area: SÃ©jour
    }
- sensor:
    unique_id: "clim2-version-Ahk2foie"
    name: "clim2 Version"
    state_topic: "clim2/Info/get"
    qos: 0
    value_template: "{{ value_json.app_version }}"
    device: {
      identifiers: ["clim2"],
      manufacturer: "rigou",
      model: "nodemcu",
      name: "Clim Séjour",
      suggested_area: SÃ©jour
    } 

# Climatiseur Chambre
- switch:
    unique_id: "clim3-power-Ogavu3ie"
    name: "clim3 Power"
    state_topic: "clim3/Power/get" # read the current state of the AC power
    command_topic: "clim3/Power/set" # turn the AC power on/off
    qos: 0
    payload_on: 1
    payload_off: 0
    optimistic: false
    device: {
      identifiers: ["clim3"],
      manufacturer: "rigou",
      model: "nodemcu",
      name: "Clim Chambre",
      suggested_area: Chambre
    }
- number:
    unique_id: "clim3-temp-Veitiez1"
    name: "clim3 Temperature"
    state_topic: "clim3/Temperature/get" # read the current temperature
    command_topic: "clim3/Temperature/set" # change the current temperature
    qos: 0
    device: {
      identifiers: ["clim3"],
      manufacturer: "rigou",
      model: "nodemcu",
      name: "Clim Chambre",
      suggested_area: Chambre
    }
- sensor:
    unique_id: "clim3-version-Ahk2foaz"
    name: "clim3 Version"
    state_topic: "clim3/Info/get"
    qos: 0
    value_template: "{{ value_json.app_version }}"
    device: {
      identifiers: ["clim3"],
      manufacturer: "rigou",
      model: "nodemcu",
      name: "Clim Chambre",
      suggested_area: Chambre
    } 
