name=rgAnalog
version=2.2.2
author=Richard Goutorbe <pub@reseau.org>
maintainer=Richard Goutorbe <pub@reseau.org>
sentence=This library implements high-performance continuous and asynchronous ADC sampling.
paragraph=This library reads the ADC continously on 2-Cores ESP32 microcontrollers. It is designed to run in Core 1, except method async_read_adc() which runs on Core 0. Using this class, you can read the ADC without waiting for analogContinuousRead() to complete, this is handy in cases where this wait would disrupt the timing of taskLoop.
category=Signal Input/Output
url=https://github.com/rigou?tab=repositories
architectures=esp32
