name=rgOTA
version=1.0
author=Richard Goutorbe <pub@reseau.org>
maintainer=Richard Goutorbe <pub@reseau.org>
sentence=OTA uploads for ESP32 with SHA256 security
paragraph=OTA uploads for ESP32 with SHA256 security
category=Network
url=https://github.com/rigou?tab=repositories
architectures=*
