name=rgDisplay
version=4.0.1
author=Richard Goutorbe <pub@reseau.org>
maintainer=Richard Goutorbe <pub@reseau.org>
sentence=This library prints text on a SSD1306 OLED display.
paragraph=This library implements simple text printing on a SSD1306 OLED display connected to I2C. It is a wrapper for Adafruit_SSD1306 library.
category=Display
url=https://github.com/rigou?tab=repositories
architectures=esp32
