# config_mqtt_dev_esp-dafde8.yaml - breadboard
# 2026-04-02

# Home Assistant naming rules :
# "unique_id" and "identifiers" can only include ASCII lowercase letters (a-z), digits (0-9), and underscores
# "name" can include any UTF-8 characters, it is the label displayed in the dashboard

# YAML syntax checker: https://www.yamllint.com/

# Breadboard
- switch: 
    # Send/receive "0" or "1" to/from the MQTT device, 
    # render the value on the dashboard as a switch
    unique_id: "esp_dafde8_power"
    name: "Power"
    state_topic: "esp-dafde8/Power/get" # read the current state of the AC power
    command_topic: "esp-dafde8/Power/set" # turn the AC power on/off
    payload_on: 1
    payload_off: 0
    optimistic: false
    qos: &DEF_QOS 0
    device: &DEVICE { 
      # the contents of this map must be the same for all entities of the esp-dafde8 device
      # so they are grouped together and show as a single device in Settings / Devices
      # set these values to match your own environment
      identifiers: ["esp_dafde8"],
      manufacturer: "rigou",
      model: "nodemcu breadboard",
      name: "esp-dafde8",
      suggested_area: Bureau
    }

- number: 
    # Send/receive an integer value to/from the MQTT device,
    # render the value on the dashboard as a slider
    unique_id: "esp_dafde8_temperature"
    name: "Temperature"
    state_topic: "esp-dafde8/Temp/get" # read the current temperature
    command_topic: "esp-dafde8/Temp/set" # change the current temperature
    qos: *DEF_QOS
    device: *DEVICE

- sensor:
    # This example shows how to receive a json object from the MQTT device
    #    and use one of its members as the value of this sensor, which will be
    #    rendered on the dashboard as read-only text with: 
    #       {{ states("sensor.esp-dafde8_version") }}
    #    the json object used here is read with the topic: "esp-dafde8/Info/get"
    #       {
    #           "app_name": "MQTTTest",
    #           "app_version": "v1.4.0",
    #           "power": 0,
    #           "temperature": 55,
    #           "button": 1,
    #           "ip": "192.168.2.164"
    #       }
    # extract the "app_version" field of the json value of the "Info" topic
    # render the value on the dashboard as a string
    unique_id: "esp_dafde8_version"
    name: "Version"
    state_topic: "esp-dafde8/Info/get"
    value_template: "{{ value_json.app_name }} {{ value_json.app_version }}"
    qos: *DEF_QOS
    device: *DEVICE

- sensor:
    # extract the "ip" field of the json value of the "Info" topic
    # render the value on the dashboard as a string
    unique_id: "esp_dafde8_ip"
    name: "Ip"
    state_topic: "esp-dafde8/Info/get"
    value_template: "{{ value_json.ip }}"
    qos: *DEF_QOS
    device: *DEVICE

- sensor:
    # Receive "0" or "1" from the MQTT device
    # render the value on the dashboard as a string
    unique_id: "esp_dafde8_button"
    name: "Button"
    state_topic: "esp-dafde8/Button/get"
    qos: *DEF_QOS
    device: *DEVICE 
