# config_mqtt_dev_esp_892a00.yaml - violet board
# 2026-04-02

# Home Assistant naming rules :
# "unique_id" and "identifiers" can only include ASCII letters (a-z, A-Z), digits (0-9), and underscores
# "name" can include any UTF-8 characters, it is the label displayed in the dashboard

# YAML syntax checker: https://www.yamllint.com/

# Violet board
- switch: 
    # Send/receive "0" or "1" to/from the MQTT device, 
    # render the value on the dashboard as a switch
    unique_id: "esp_892a00_power"
    name: "Power"
    state_topic: "esp-892a00/Power/get" # read the current state of the AC power
    command_topic: "esp-892a00/Power/set" # turn the AC power on/off
    qos: &DEF_QOS 0
    payload_on: 1
    payload_off: 0
    optimistic: false
    device: { 
      # the contents of this map must be the same for all entities of the esp_892a00 device
      # so they are grouped together and show as a single device in Settings / Devices
      # set these values to match your own environment
      identifiers: &DEV_IDS ["esp_892a00"],
      manufacturer: &DEV_MAN "rigou",
      model: &DEV_MOD "nodemcu violet board",
      name: &DEV_NAM "esp-892a00",
      suggested_area: &DEV_ARE Bureau
    } 

- number: 
    # Send/receive an integer value to/from the MQTT device,
    # render the value on the dashboard as a slider
    unique_id: "esp_892a00_temperature"
    name: "Temperature"
    state_topic: "esp-892a00/Temp/get" # read the current temperature
    command_topic: "esp-892a00/Temp/set" # change the current temperature
    qos: *DEF_QOS
    device: { identifiers: *DEV_IDS, manufacturer: *DEV_MAN, model: *DEV_MOD, name: *DEV_NAM, suggested_area: *DEV_ARE }

- sensor:
    # This example shows how to receive a json object from the MQTT device
    #    and use one of its members as the value of this sensor, which will be
    #    rendered on the dashboard as read-only text with: 
    #       {{ states("sensor.esp_892a00_version") }}
    #    the json object used here is read with the topic: "esp-892a00/Info/get"
    #       {
    #           "app_name": "MQTTTest",
    #           "app_version": "v1.4.0",
    #           "power": 0,
    #           "temperature": 55,
    #           "button": 1,
    #           "ip": "192.168.2.164"
    #       }
    # extract the "app_version" field of the json value of the "Info" topic
    # render the value on the dashboard as a string
    unique_id: "esp_892a00_version"
    name: "Version"
    state_topic: "esp-892a00/Info/get"
    qos: *DEF_QOS
    value_template: "{{ value_json.app_name }} {{ value_json.app_version }}"
    device: { identifiers: *DEV_IDS, manufacturer: *DEV_MAN, model: *DEV_MOD, name: *DEV_NAM, suggested_area: *DEV_ARE }

- sensor:
    # extract the "ip" field of the json value of the "Info" topic
    # render the value on the dashboard as a string
    unique_id: "esp_892a00_ip"
    name: "Ip"
    state_topic: "esp-892a00/Info/get"
    qos: *DEF_QOS
    value_template: "{{ value_json.ip }}"
    device: { identifiers: *DEV_IDS, manufacturer: *DEV_MAN, model: *DEV_MOD, name: *DEV_NAM, suggested_area: *DEV_ARE }

- sensor:
    # Receive "0" or "1" from the MQTT device
    # render the value on the dashboard as a string
    unique_id: "esp_892a00_button"
    name: "Button"
    state_topic: "esp-892a00/Button/get"
    qos: *DEF_QOS
    device: { identifiers: *DEV_IDS, manufacturer: *DEV_MAN, model: *DEV_MOD, name: *DEV_NAM, suggested_area: *DEV_ARE }
