name=rgCsv
version=1.6.0
author=Richard Goutorbe <pub@reseau.org>
maintainer=Richard Goutorbe <pub@reseau.org>
sentence=A CSV library.
paragraph=This library loads a CSV file in an array and offers methods to update the array and save the changes.
category=Data Storage
url=https://github.com/rigou?tab=repositories
architectures=esp32
