name=rgRng
version=1.1.2
author=Richard Goutorbe <pub@reseau.org>
maintainer=Richard Goutorbe <pub@reseau.org>
sentence=A pseudo random generator library.
paragraph=This Xorshift random number generator is derived from original code found at https://en.wikipedia.org/wiki/Xorshift#xorwow .
category=Data Processing
url=https://github.com/rigou?tab=repositories
architectures=*
