name=rgSoundSensor
version=1.0
author=Richard Goutorbe <pub@reseau.org>
maintainer=Richard Goutorbe <pub@reseau.org>
sentence=Hand claps detection with Aliexpress Sound Sensor Module KY-038 LM393
paragraph=Hand claps detection with Aliexpress Sound Sensor Module KY-038 LM393
category=Sensors
url=https://github.com/rigou?tab=repositories
architectures=*
