# config_mqtt_MQTTTest.yml - Send/receive data to/from ESP32 over MQTT
# 2026-03-29
- switch: 
    # Send/receive "0" or "1" to/from the MQTT device, 
    # render the value on the dashboard as a switch
    unique_id: "esp-dafde8-power"
    name: "esp-dafde8 Power"
    state_topic: "esp-dafde8/Power/get" # read the current state of the AC power
    command_topic: "esp-dafde8/Power/set" # turn the AC power on/off
    qos: 0
    payload_on: 1
    payload_off: 0
    optimistic: false
    device: { 
      # the contents of this map must be the same for all entities of the esp-dafde8 device
      # so they are grouped together and show as a single device in Settings / Devices
      # set these values to match your own environment
      identifiers: ["esp-dafde8"],
      manufacturer: "rigou",
      model: "nodemcu",
      name: "esp-dafde8",
      suggested_area: Bureau
    } 
- number: 
    # Send/receive an integer value to/from the MQTT device,
    # render the value on the dashboard as a slider
    unique_id: "esp-dafde8-temperature"
    name: "esp-dafde8 Temperature"
    state_topic: "esp-dafde8/Temp/get" # read the current temperature
    command_topic: "esp-dafde8/Temp/set" # change the current temperature
    qos: 0
    device: {
      identifiers: ["esp-dafde8"],
      manufacturer: "rigou",
      model: "nodemcu",
      name: "esp-dafde8",
      suggested_area: Bureau
    }
- sensor:
    # This example shows how to receive a json object from the MQTT device
    #    and use one of its members as the value of this sensor, which will be
    #    rendered on the dashboard as read-only text with: 
    #       {{ states("sensor.esp-dafde8_version") }}
    #    the json object used here is read with the topic: "esp-dafde8/Info/get"
    #       {
    #           "app_name": "MQTTTest",
    #           "app_version": "v1.4.0",
    #           "power": 0,
    #           "temperature": 55,
    #           "button": 1,
    #           "ip": "192.168.2.164"
    #       }
    # extract the "app_version" field of the json value of the "Info" topic
    # render the value on the dashboard as a string
    unique_id: "esp-dafde8-version"
    name: "esp-dafde8 Version"
    state_topic: "esp-dafde8/Info/get"
    qos: 0
    value_template: "{{ value_json.app_version }}"
    device: {
      identifiers: ["esp-dafde8"],
      manufacturer: "rigou",
      model: "nodemcu",
      name: "esp-dafde8",
      suggested_area: Bureau
    } 
- sensor:
    # extract the "ip" field of the json value of the "Info" topic
    # render the value on the dashboard as a string
    unique_id: "esp-dafde8-ip"
    name: "esp-dafde8 Ip"
    state_topic: "esp-dafde8/Info/get"
    qos: 0
    value_template: "{{ value_json.ip }}"
    device: {
      identifiers: ["esp-dafde8"],
      manufacturer: "rigou",
      model: "nodemcu",
      name: "esp-dafde8",
      suggested_area: Bureau
    } 
- sensor:
    # Receive "0" or "1" from the MQTT device
    # render the value on the dashboard as a string
    unique_id: "esp-dafde8-button"
    name: "esp-dafde8 Button"
    state_topic: "esp-dafde8/Button/get"
    qos: 0
    device: {
      identifiers: ["esp-dafde8"],
      manufacturer: "rigou",
      model: "nodemcu",
      name: "esp-dafde8",
      suggested_area: Bureau
    } 
# config_mqtt_MQTTTest.yml ----------------------------------------------------



# Climatiseur Bureau
- switch:
    unique_id: "clim1-power-ooyeRai1"
    name: "clim1 Power"
    state_topic: "clim1/Power/get" # read the current state of the AC power
    command_topic: "clim1/Power/set" # turn the AC power on/off
    qos: 0
    payload_on: 1
    payload_off: 0
    optimistic: false
    device: {
      identifiers: ["clim1"],
      manufacturer: "rigou",
      model: "nodemcu",
      name: "Clim Bureau",
      suggested_area: Bureau
    }
- number:
    unique_id: "clim1-temp-aibiToo3"
    name: "clim1 Temperature"
    state_topic: "clim1/Temperature/get" # read the current temperature
    command_topic: "clim1/Temperature/set" # change the current temperature
    qos: 0
    device: {
      identifiers: ["clim1"],
      manufacturer: "rigou",
      model: "nodemcu",
      name: "Clim Bureau",
      suggested_area: Bureau
    }
- sensor:
    unique_id: "clim1-version-Ahk2fooj"
    name: "clim1 Version"
    state_topic: "clim1/Info/get"
    qos: 0
    value_template: "{{ value_json.app_version }}"
    device: {
      identifiers: ["clim1"],
      manufacturer: "rigou",
      model: "nodemcu",
      name: "Clim Bureau",
      suggested_area: Bureau
    } 

# Climatiseur Séjour
- switch:
    unique_id: "clim2-power-eiGhej0y"
    name: "clim2 Power"
    state_topic: "clim2/Power/get" # read the current state of the AC power
    command_topic: "clim2/Power/set" # turn the AC power on/off
    qos: 0
    payload_on: 1
    payload_off: 0
    optimistic: false
    device: {
      identifiers: ["clim2"],
      manufacturer: "rigou",
      model: "nodemcu",
      name: "Clim Séjour",
      suggested_area: SÃ©jour
    }
- number:
    unique_id: "clim2-temp-eisei9Ie"
    name: "clim2 Temperature"
    state_topic: "clim2/Temperature/get" # read the current temperature
    command_topic: "clim2/Temperature/set" # change the current temperature
    qos: 0
    device: {
      identifiers: ["clim2"],
      manufacturer: "rigou",
      model: "nodemcu",
      name: "Clim Séjour",
      suggested_area: SÃ©jour
    }
- sensor:
    unique_id: "clim2-version-Ahk2foie"
    name: "clim2 Version"
    state_topic: "clim2/Info/get"
    qos: 0
    value_template: "{{ value_json.app_version }}"
    device: {
      identifiers: ["clim2"],
      manufacturer: "rigou",
      model: "nodemcu",
      name: "Clim Séjour",
      suggested_area: SÃ©jour
    } 

# Climatiseur Chambre
- switch:
    unique_id: "clim3-power-Ogavu3ie"
    name: "clim3 Power"
    state_topic: "clim3/Power/get" # read the current state of the AC power
    command_topic: "clim3/Power/set" # turn the AC power on/off
    qos: 0
    payload_on: 1
    payload_off: 0
    optimistic: false
    device: {
      identifiers: ["clim3"],
      manufacturer: "rigou",
      model: "nodemcu",
      name: "Clim Chambre",
      suggested_area: Chambre
    }
- number:
    unique_id: "clim3-temp-Veitiez1"
    name: "clim3 Temperature"
    state_topic: "clim3/Temperature/get" # read the current temperature
    command_topic: "clim3/Temperature/set" # change the current temperature
    qos: 0
    device: {
      identifiers: ["clim3"],
      manufacturer: "rigou",
      model: "nodemcu",
      name: "Clim Chambre",
      suggested_area: Chambre
    }
- sensor:
    unique_id: "clim3-version-Ahk2foaz"
    name: "clim3 Version"
    state_topic: "clim3/Info/get"
    qos: 0
    value_template: "{{ value_json.app_version }}"
    device: {
      identifiers: ["clim3"],
      manufacturer: "rigou",
      model: "nodemcu",
      name: "Clim Chambre",
      suggested_area: Chambre
    } 
