name=rgLed
version=2.0.1
author=Richard Goutorbe <pub@reseau.org>
maintainer=Richard Goutorbe <pub@reseau.org>
sentence=A non blocking library for blinking leds.
paragraph=This library provides methods to blink or flash a gpio in a non blocking way.
category=Signal Input/Output
url=https://github.com/rigou?tab=repositories
architectures=*
